#!/bin/env zsh

./lint

current_version=$(jq -r '.version' plugin.json)
IFS='.' read -r major minor patch <<< "$current_version"
((patch++))
new_version="$major.$minor.$patch"
sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" plugin.json

git add -A
git commit -m "auto"
latest_tag=$(git describe --tags --abbrev=0)
# new_version=$(python3 -c "import re; major, minor, patch = re.match('v(\d+)\.(\d+)\.(\d+)', '${latest_tag}').groups(); patch = int(patch) + 1; print(f'v{major}.{minor}.{patch}')")
git tag v${new_version}
git push origin v${new_version}
git push gitee v${new_version}
git push origin
git push gitee
